### ISSUE TITLE
Backup accidental deletion  makes it impossible to restore app and problem with flags

### ISSUE THREAD

**Issue by ginkuji** [emiyl/HBInjector#3]
I. Here I provided system apps eboot to restore from the application in case the backup is deleted from ux0:data/hbinjector/titleid  
https://drive.google.com/open?id=1ktDmsVplbjsZaowe-nrRDEaJ0sH4IUin

Maybe a new update might provide the user to use the eboot backups independent from the one's being backup by the hbinjector. This will prove more useful in restoring files. 

II. Flags issues kept on popping. Need to delete files from ux0:data/hbinjector/flags in order to inject/restore apps

**Comment by gnmmarechal** [comment]
Aight. I'll be mirroring the files myself. I guess I could add the og eboots to the app, but.... I'll think about it.

**Comment by emiyl** [comment]
Flag issues have been fixed in 1.2.6 thanks to [StepS-](https://github.com/StepS-)
